---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myfinbudget-pv
  namespace: myfinbudget
spec:
  capacity:
   storage: 2Gi
  accessModes:
   - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myfinbudget-db
  namespace: myfinbudget
  labels:
    app: myfinbudget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

