# https://kubernetes.io/docs/concepts/storage/persistent-volumes/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myfinbudget-db
  namespace: myfinbudget
  labels:
    app: myfinbudget
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

