# .sops.yaml
creation_rules:
  - path_regex: secrets/.*\.secret\.sops\.ya?ml
    encrypted_regex: '^(data|stringData)$'
    age: 
      - age146648exz5kqh3p026wp9ncts9x2we4uh3qzxyy7k8zazreczr5fsegazt8
