apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: gatus
      version: "1.4.3"
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: monitoring
      interval: 12h
  values:
    persistence:
      enabled: true
      storageClassName: nfs-client
    config:
      endpoints:
        ## Public
        - name: Google
          url: https://www.google.com
          group: Public
          conditions:
            - "[STATUS] == 200"
        ## Homelab
        - name: Grafana
          url: https://kubegrafana.mbhlabs.uk
          group: Homelab
          conditions:
            - "[STATUS] == 200"
        - name: Prometheus
          url: https://kubeprom.mbhlabs.uk
          group: Homelab
          conditions:
            - "[STATUS] == 200"
        ## Home Services
        - name: NAS
          url: https://nas.mbhlabs.uk
          group: Home Services
          conditions:
            - "[STATUS] == 200"
        ## Physical Devices
        - name: Talos01
          url: icmp://talos01.mbhlabs.uk
          group: Physical Devices
          conditions:
            - "[CONNECTED] == true"
        - name: Talos02
          url: icmp://talos02.mbhlabs.uk
          group: Physical Devices
          conditions:
            - "[CONNECTED] == true"
        - name: Talos03
          url: icmp://talos03.mbhlabs.uk
          group: Physical Devices
          conditions:
            - "[CONNECTED] == true"
