apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: gatus
      version: "1.4.3"
      sourceRef:
        kind: HelmRepository
        name: twin
        namespace: monitoring
      interval: 12h
  values:
    config:
      endpoints:
        ## Public
        - name: Google
          url: https://www.google.com
          group: Public
          conditions:
            - "[STATUS] == 200"
        ## Homelab
        - name: Grafana
          url: https://kubegrafana.mbhlabs.uk
          group: Homelab
          conditions:
            - "[STATUS] == 200"
        - name: Prometheus
          url: https://kubeprom.mbhlabs.uk
          group: Homelab
          conditions:
            - "[STATUS] == 200"
