apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatus
  namespace: monitoring
spec: 
  interval: 30m 
  chart: 
    spec: 
      chart: gatus
      version: "1.4.3"
      sourceRef: 
        kind: HelmRepository 
        name: twin
        namespace: monitoring 
      interval: 12h
  values:
    config:
      endpoints: {}