apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 5m
  path: ./apps/overlays/talos-cluster
  prune: true
  wait: true
  timeout: 3m
  sourceRef:
    kind: GitRepository
    name: repo
  dependsOn:
    - name: infra
  targetNamespace: web
