apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gitea
  namespace: gitea
spec:
  interval: 30m
  chart:
    spec:
      chart: gitea
      version: "2.2.0"
      sourceRef:
        kind: HelmRepository
        name: gitea
        namespace: gitea
      interval: 12h
  values:
    installCRDs: true
