apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: postgresql
    namespace: database
  upgrade:
    force: true
