apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: postgresql
  namespace: database
spec:
  interval: 30m
  chart:
    spec:
      chart: postgresql
      version: "18.0.17"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: database
      interval: 12h
