apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  clusterIP: None  # This makes the service headless (useful for StatefulSet)
  ports:
    - port: 5432
      name: postgres
  selector:
    app: postgres