apiVersion: helm.tookit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  timeout: 20m
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    force: true
    crds: Create
  chart:
    spec:
      chart: cilium
      version: 1.16.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  values:
    # kube-proxy is present, so do NOT replace it
    kubeProxyReplacement: false
    masquerade: true
    hubble:
      enabled: false
      relay:
        enabled: false
      ui:
        enabled: false
