apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 5m
  timeout: 20m
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
    crds: Create
  upgrade:
    remediation:
      retries: 3
    force: true
    crds: Create
  chart:
    spec:
      chart: cilium
      version: 1.16.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
