apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  releaseName: cilium
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.16.6
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: kube-system
  values:
    kubeProxyReplacement: "partial"
    hubble:
      enabled: false