apiVersion: "cilium.io/v2alpha1"
kind: CiliumL2AnnouncementPolicy
metadata:
  name: l2-policy
  namespace: kube-system
spec:
  # IMPORTANT: if externalIPss is desired, externalIPs.enabled=true must be set in values.yaml
  externalIPs: false
  loadBalancerIPs: true