apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nfs-client-provisioner
  name: nfs-client-provisioner
spec:
  template:
    spec:
      containers:
        - name: nfs-client-provisioner
          env:
            - name: NFS_SERVER
              value: 192.168.10.5
            - name: NFS_PATH
              value: /volume2/talos-cluster
      volumes:
        - name: nfs-client-root
          nfs:
            server: 192.168.10.5
            path: /volume2/talos-cluster