---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: prometheus
  namespace: monitoring
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
  hostnames: ["kubeprom.mbhlabs.uk"]
  rules:
  - backendRefs:
    - name: kube-prometheus-stack-prometheus
      port: 9090