apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-uptime-kuma
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-client
  mountOptions:
    - hard
    - nfsvers=4.1