apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec: 
  interval: 30m 
  chart: 
    spec: 
      chart: uptime-kuma 
      version: "2.22.0" 
      sourceRef: 
        kind: HelmRepository 
        name: uptime-kuma 
        namespace: monitoring 
      interval: 12h
  values:
    volume:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
      storageClassName: nfs-client

    podSecurityContext:
      runAsNonRoot: false
      runAsUser: 1000
      runAsGroup: 1000