apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: uptime-kuma
      version: "2.22.0"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: monitoring
      interval: 12h
  values:
    mariadb:
      enabled: true
      auth:
        database: uptime_kuma
        username: uptime_kuma
        password: "temp"
        rootPassword: "temp"
    podSecurityContext:
      fsGroup: 1000
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
    volume:
      enabled: true
      accessMode: ReadWriteOnce
      size: 4Gi
      storageClassName: nfs-client