apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: uptime-kuma
      version: "2.24.X"
      sourceRef:
        kind: HelmRepository
        name: uptime-kuma
        namespace: monitoring
      interval: 12h
  values:
    podSecurityContext:
      fsGroup: 1000

    # securityContext:
    #   capabilities:
    #     drop:
    #     - ALL
    #   readOnlyRootFilesystem: true
    #   runAsNonRoot: true
    #   runAsUser: 1000
