apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  #settings.yaml: |
  #  providers:
  #    longhorn:
  #      url: https://longhorn.my.network
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - Network Tools:
        - Traefik Dashboard:
            href: https://dashboard.mbhlabs.uk/dashboard/
            description: Traefik UI Dashboard
        - Unifi Dashboard:
            href: https://unifi.ui.com
            description: Unifi Console

    - Monitoring:
        - Grafana:
            href: https://kubegrafana.mbhlabs.uk
            description: Grafana Monitoring Dashboard
        - Gatus
            href: https://gatus.mbhlabs.uk
            description: Gatus Uptime Monitoring
        - Prometheus
            href: https://kubeprom.mbhlabs.uk
            description: Prometheus Dashboard

    - Storage:
        - UGreen NAS:
            href: https://nas.mbhlabs.uk
            description: NAS UI
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - resources:
        backend: resources
        expanded: true
        cpu: true
        memory: true
        network: default
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
