---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: pgadmin
  namespace: database
spec:
  parentRefs:
    - name: traefik-gateway
      namespace: traefik
  hostnames: ["pgadmin.mbhlabs.uk"]
  rules:
    - backendRefs:
        - name: pgadmin-pgadmin4
          port: 80
