apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pgadmin
  namespace: database
spec:
  interval: 30m
  upgrade:
    force: true
  chart:
    spec:
      chart: pgadmin4
      version: "1.50.0"
      sourceRef:
        kind: HelmRepository
        name: pgadmin4
        namespace: database
      interval: 12h

