---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: gatus
  namespace: monitoring
spec:
  parentRefs:
  - name: traefik-gateway
    namespace: traefik
  hostnames: ["gatus.mbhlabs.uk"]
  rules:
  - backendRefs:
    - name: gatus
      port: 80