# values.yaml
api:
  dashboard: true
  insecure: true
ingressRoute:
  dashboard:
    enabled: true
    matchRule: Host(`dashboard.mbhlabs.uk`)
    entryPoints:
      - web
providers:
  kubernetesGateway:
    enabled: true
gateway:
  listeners:
    web:
      namespacePolicy:
        from: All